### ISSUE TITLE
Request: Change of translation concept

### ISSUE THREAD

**Issue by Nowi5** [GrafiteInc/CMS#132]
Hi,

I have used this CMS now in every detail for a multi language page and the translatable function including all the if/else in the view is not very good. This includes also the possibility to search across pages and blog entries. The database selection is not very efficient.

What do you think about to extend the config file by the to allowed languages and take this as an additional key in all tables. So we do not need an own translatable function and table anymore. Of course the repositories need to be extended and the where condition need to be adjusted, but if you like I can do so.

ID LID Language Values...
1  1  EN  My Text
2  1  DE  Mein Text
3  1  FR  ...
4  4  EN Another example
5  4  DE Ein weiteres Beispiel

What do you think about that?

The only issue will be, that in case of an update the already existing translations have to be migrated somehow.

**Comment by kirapwn** [comment]
I do not fully understand what you mean. But I have some issues with the translation concept too.

Lets say you want to have three languages. I have few requirements to how this should work:

Assume you have a website with languages: DE, PL, EN.

- Homepage should always be in the user browser language unless its not in the supported languages, than it uses fallback language
- Links to pages should be as /de/page-slug etc. (this is already possible)
- There should be Laravel relation to the parent page translation model so you can go to other translations if needed (link to other language directly from the same page)
- If you have a view with displayed title lets say `$item->title`, it should be possible to use `$item->trans()->title` so it gets the value for current `app()->getLocale()`
- Finding the slug by opening directly a link /de/page-slug should not be done by SQL LIKE %% query that we currently have. Ultimately it should be using `uri` table for stored slug (page-slug) with corresponding locale so its easy to index and go up to `parent()` which would be essentially the `translations` instance
- Menu items should be translatable as currently you would have to get the actual page and use its title instead of `Menu` model

**Comment by Nowi5** [comment]
Yes, I'm with you.
The only difference for me is `$item->title` should always give the translation directly in user language (if given otherwise fallback). I don't like to see in the view always this if/else.

**Comment by mlantz** [comment]
Translations are my next thing to refactor for improvements - I appreciate all the suggestions :)

**Comment by Nowi5** [comment]
Any updates on that? Do you need help?

**Comment by Nowi5** [comment]
Hi, I trust you are doing fine. Do you have already a rough timeline in your head?

**Comment by mlantz** [comment]
In the latest release menu links are now translatable

**Comment by Nowi5** [comment]
This is fine thank you for that. I think that was not the only questions. Do you have thought about the total redesign of the translation?

**Comment by mlantz** [comment]
I found a bug in the menu due to translations which will have a fix coming soon. 

@Nowi5 and @kirapwn I've removed the LIKE query (I agree that was a poor choice). I can set up a relational aspect to the pages, so you can easily get links to other languages of the same entity. 

Total redesign's are big requests and I'm not a fan of having each module's table needing adjustments to handle the suggestion above, the repositories are in place in order to set the language on the request so that the page you get is the translated one. 
@Nowi5 you mention the `if/else` I just encountered this, and have adjusted the `translation` method to fall back to the default Model if it cannot find a translation.
