### ISSUE TITLE
All admin urls 404

### ISSUE THREAD

**Issue by REPTILEHAUS** [GrafiteInc/CMS#149]
Trying to navigate from backend to one of the admin urls and hit 404 pages

**Comment by mnwalker** [comment]
@REPTILEHAUS is your install in a subfolder?
If so then I have the same and is the cause.

Lots of the links are hard coded to site relative paths
eg.
action="'/admin/users/invite"
Which needs to be
action="{{ URL::to('/admin/users/invite') }}"

Can manually fix these in views etc as you hit each error but would be best if was tackled in the project.
@mlantz any reason not to do this? Want me to prepare a PR?

**Comment by mlantz** [comment]
Please do @mnwalker, sometimes things are just missed.... ¯\_(ツ)_/¯ lets do `url()` though

**Comment by REPTILEHAUS** [comment]
@mlantz @mnwalker  lads this isnt fixed

**Comment by mnwalker** [comment]
@REPTILEHAUS please check the notes below from my PR, it may affect your ongoing issue https://github.com/GrafiteInc/CMS/pull/152

Since the bulk of these files are in the install section this fix will only help fresh installs.
Existing installs will need to copy the relevant files from this package over their own views, any changed files will need to be merged manually.
