### ISSUE TITLE
Licenses WYSIWYG Editor

### ISSUE THREAD

**Issue by Nowi5** [GrafiteInc/CMS#165]
Hi,

when I see it right you are using Redactor as WYSIWYG Editor.
Can you explain me how this is licensed?
https://imperavi.com/redactor/buy/

I would guess everybody who uses this package would need to buy a own one, right?

Thanks

**Comment by mlantz** [comment]
I bought an OEM license with them to allow it to be in open source applications that I offer.

**Comment by Nowi5** [comment]
Yeah... not such easy as everybody is using that in there own application and may even implement this in own SaaS Platform. **Please update CMS/LICENSE.md and add the OEM license into that.**

**Comment by mlantz** [comment]
Based on what I'm reading in [this](https://imperavi.com/redactor/license/) since I've acquired the OEM license and have given users of Grafite CMS access to this version of it, they may use it within the Grafite CMS. If you choose to build a SaaS app and integrate the Grafite CMS into that application then  that is also acceptable. The only catch is that you're not permitted to extract it and offer it individually as a product or otherwise, also as a non-license holder you are able to make requests for support.
