### ISSUE TITLE
Localization using FormMaker

### ISSUE THREAD

**Issue by ghost** [GrafiteInc/CMS#86]
How do we do localization using the FormMaker with the fields listed in the config files?   We can't use Translator in a config file, so not sure what the plan is.  Thanks

**Comment by mlantz** [comment]
Hey @cjrigdon there are a few ways to address this issue. First, the admin screens are in the vendor view directory which means you can change them, this means you could opt out of using FormMaker script and setup custom forms. The other option is rather than have the FormMaker grab the config value of the forms you could have it grab a method result where you run translations on the form config keys.

ex.

Change the following (resources/vendor/quarx/modules/blogs/create.blade.php)
```
{!! FormMaker::fromTable('blogs', Config::get('quarx.forms.blog')) !!}
```

to 

```
{!! FormMaker::fromTable('blogs', app(CustomService:class)->translate(Config::get('quarx.forms.blog'))) !!}
```
